services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 81:80
      - 444:443
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: administrador0
      POSTGRES_DB: inventario_festo
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./:/var/www
    depends_on:
      - db

  node:
    image: node:16-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: sh /var/www/node_start.sh
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
